#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright © 2014, IOhannes m zmölnig, IEM

# This file is part of striem
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with striem.  If not, see <http://www.gnu.org/licenses/>.


from PySide.QtGui import QDialog, QApplication, QVBoxLayout, QIcon
from PySide.QtCore import Qt
import gui, core


if __name__ == '__main__':
    import sys
    #if args.logfile is None:
    #        args.logfile='stderr'
    #l = logger.logger(args.logfile)
    import gobject
    gobject.threads_init()
    # Create the Qt Application
    app = QApplication(sys.argv)
    #translator = Translator(app)

    # create the streamer
    streamer = core.streamer()

    # Create and show the form
    form = gui.striem(app=app, streamer=streamer)

    streamer.setGui(form)

    form.show()
    # Run the main Qt loop
    sys.exit(app.exec_())
